// <auto-generated />
namespace Jackson.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class postwithimages2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(postwithimages2));
        
        string IMigrationMetadata.Id
        {
            get { return "201403101819287_postwithimages2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
